### ISSUE TITLE
By default searches my co's enterprise github instead of public github

### ISSUE THREAD

**Issue by kumavis** [ushis/github-search-chrome-extension#1]
if i type `gh[tab]` it searches `gh.mycompany.com` instead of `github.com`.
How can I change this?

**Comment by ushis** [comment]
Hey,

the URIs are hardcoded to https://api.github.com and https://github.com. See: https://github.com/ushis/github-search-chrome-extension/blob/master/github-search.js#L7

Talk to your admins, maybe they redirect API calls to your local GitHub.

Cheers, ushi
