### ISSUE TITLE
Support jumping to a known repository

### ISSUE THREAD

**Issue by aleclarson** [ushis/github-search-chrome-extension#2]
`gh <TAB> go username/repo-name`

Maybe even have a "search history" with autocomplete.

Anyways, thanks for the interesting extension (yes, I see that this is 4 years dormant). 😄

**Comment by ushis** [comment]
hey @aleclarson 

as far as i remember (i dont use this extension anymore) both features should already be implemented. Perhaps they are broken, i dont know :smile: 

To go to a repo, type: `gh <TAB> rails/rails` select the repo and `<ENTER>` 

Search the history: `gh <TAB> :something` Note the colon...

You can even search for users: `gh <TAB> @rails`

But as i said, maybe its all broken :smile:

**Comment by aleclarson** [comment]
@ushis Awesome! I'll send a pull request when I get the time. 😉

**Comment by aleclarson** [comment]
Also, is there any reason why you don't use this anymore?

**Comment by ushis** [comment]
@aleclarson i dont know why i stopped using it, maybe it was broken and i was too lazy to fix it. today the default github search engine is just good enough for me.
